apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: ray-configmap
  namespace: application
data:
  # example of a simple property defined using --from-literal
  example.property.1: test
  example.property.2: test2
  # example of a complex property defined using --from-file
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3
