{{- if hasKey .Values.config "secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-service.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range .Values.config.secrets }}
  {{ .name }}: {{ .value | quote}}
{{- end }}
{{- if .Values.sidecars.sso.enabled }}
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.sidecars.sso.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.sidecars.sso.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.sidecars.sso.cookieSecret | quote }}
{{- end }}
{{- end }}
