# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 3

image:
  repository: kornkitti/express-hello-world

ingress:
  enabled: false

redis:
  enabled: false

container:
  port: 8080

config:
  envFromConfigMaps: ["ray-configmap"]
